<?php
require_once __DIR__ . '/includes/auth.php';
require_role(['admin','staff']);
$page_title='Billing'; $order=null; $items=[];
function bill_icon($name){$n=strtolower($name);if(strpos($n,'tomato')!==false)return '🍅';if(strpos($n,'potato')!==false)return '🥔';if(strpos($n,'onion')!==false)return '🧅';if(strpos($n,'carrot')!==false)return '🥕';if(strpos($n,'cucumber')!==false)return '🥒';if(strpos($n,'capsicum')!==false)return '🫑';return '🥬';}
if(isset($_GET['receipt'])){ $rid=(int)$_GET['receipt'];$st=$pdo->prepare("SELECT * FROM orders WHERE id=?");$st->execute([$rid]);$ro=$st->fetch();if(!$ro)exit('Receipt not found.');$it=$pdo->prepare("SELECT * FROM order_items WHERE order_id=?");$it->execute([$rid]);$ri=$it->fetchAll();$sub=array_sum(array_column($ri,'subtotal'));$discount=(float)$ro['discount_amount'];?><!doctype html><html><head><meta charset="utf-8"><title>Receipt #<?=$rid?></title><link rel="stylesheet" href="../assets/css/style.css"><link rel="stylesheet" href="admin.css"><style>@media print{.no-print{display:none!important}}body{padding:30px;background:#f7f9f8}.receipt{max-width:620px;margin:auto;background:#fff;padding:28px;border:1px solid #e3e9e5;border-radius:14px}.receipt table{width:100%;border-collapse:collapse}.receipt th,.receipt td{padding:10px;border-bottom:1px solid #edf0ee;text-align:left}</style></head><body><div class="receipt"><h2><?=h(SITE_NAME)?></h2><p>Bill #<?=$rid?> · <?=h(format_ist($ro['created_at']))?></p><hr><p><?=h($ro['customer_name'])?><br><?=h($ro['phone'])?></p><table><tr><th>Item</th><th>Qty</th><th>Total</th></tr><?php foreach($ri as $r):?><tr><td><?=h($r['name'])?></td><td><?=$r['quantity']?></td><td>₹<?=number_format($r['subtotal'],2)?></td></tr><?php endforeach;?></table><hr><p>Subtotal: ₹<?=number_format($sub,2)?><br>Discount (<?=number_format($sub>0?$discount/$sub*100:0,2)?>%): -₹<?=number_format($discount,2)?><br><strong>Total: ₹<?=number_format($ro['total_amount'],2)?></strong></p><button class="admin-btn admin-btn-primary no-print" onclick="window.print()">Print Receipt</button> <a class="admin-btn no-print" href="billing.php">New Bill</a></div></body></html><?php exit; }
if($_SERVER['REQUEST_METHOD']==='POST' && isset($_POST['checkout'])){require_csrf();$name=trim($_POST['customer_name']??'Walk-in Customer');$email=trim($_POST['email']??'walkin@local');$phone=trim($_POST['phone']??'0000000000');$address=trim($_POST['address']??'Store counter');$discountPct=max(0,min(100,(float)($_POST['discount_percent']??0)));$payment=in_array($_POST['payment_method']??'', ['cash','upi_qr'], true)?$_POST['payment_method']:'cash';$cart=$_SESSION['billing_cart']??[];if(!$cart)$_SESSION['flash']=['type'=>'error','message'=>'Add at least one item.'];else{try{$pdo->beginTransaction();$subtotal=0;$locked=[];$sel=$pdo->prepare("SELECT id,name,unit,price,sale_price,cost_price,stock FROM vegetables WHERE id=? FOR UPDATE");foreach($cart as $id=>$qty){$id=(int)$id;$qty=(int)$qty;if($qty<1)continue;$sel->execute([$id]);$v=$sel->fetch();if(!$v||$v['stock']<$qty)throw new Exception('Insufficient stock for '.($v['name']??'item'));$use=($v['sale_price']!==null&&$v['sale_price']<$v['price'])?(float)$v['sale_price']:(float)$v['price'];$subtotal+=round($use*$qty,2);$locked[]=['v'=>$v,'qty'=>$qty,'price'=>$use];}$discount=round($subtotal*$discountPct/100,2);$total=$subtotal-$discount;$st=$pdo->prepare("INSERT INTO orders (customer_name,email,phone,address,total_amount,payment_method,payment_status,order_status,discount_amount) VALUES (?,?,?,?,?,?, 'paid','placed',?)");$st->execute([$name,$email,$phone,$address,$total,$payment,$discount]);$oid=$pdo->lastInsertId();$it=$pdo->prepare("INSERT INTO order_items (order_id,vegetable_id,name,price,quantity,subtotal,cost_price) VALUES (?,?,?,?,?,?,?)");$up=$pdo->prepare("UPDATE vegetables SET stock=stock-? WHERE id=? AND stock>=?");$mv=$pdo->prepare("INSERT INTO inventory_movements (vegetable_id,movement_type,quantity,reference_id,notes,created_by) VALUES (?,'sale',?,?,?,?)");foreach($locked as $x){$v=$x['v'];$q=$x['qty'];$line=round($x['price']*$q,2);$it->execute([$oid,$v['id'],$v['name'],$x['price'],$q,$line,$v['cost_price']]);$up->execute([$q,$v['id'],$q]);if($up->rowCount()!==1)throw new Exception('Stock changed during checkout. Please retry.');$mv->execute([$v['id'],-$q,$oid,'Billing sale',$_SESSION['admin_id']]);}$pdo->commit();unset($_SESSION['billing_cart']);$order=$oid;$_SESSION['flash']=['type'=>'success','message'=>"Bill #$oid created."]; }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$_SESSION['flash']=['type'=>'error','message'=>'Checkout failed: '.$e->getMessage()];}}}
if($_SERVER['REQUEST_METHOD']==='POST' && isset($_POST['add_item'])){require_csrf();$id=(int)$_POST['vegetable_id'];$q=max(1,(int)$_POST['quantity']);$st=$pdo->prepare("SELECT id,stock FROM vegetables WHERE id=?");$st->execute([$id]);$v=$st->fetch();if($v&&$v['stock']>=$q){$_SESSION['billing_cart'][$id]=($_SESSION['billing_cart'][$id]??0)+$q;}else$_SESSION['flash']=['type'=>'error','message'=>'Invalid product or insufficient stock.'];header('Location: billing.php');exit;}
if(isset($_GET['clear'])){unset($_SESSION['billing_cart']);header('Location: billing.php');exit;}
$q=$pdo->prepare("SELECT id,name,unit,price,sale_price,stock FROM vegetables WHERE is_active=1 AND stock>0 ORDER BY name");$q->execute();$products=$q->fetchAll();$cart=$_SESSION['billing_cart']??[];$lines=[];$subtotal=0;if($cart){$q=$pdo->prepare("SELECT id,name,unit,price,sale_price,stock FROM vegetables WHERE id=?");foreach($cart as $id=>$qty){$q->execute([(int)$id]);if($v=$q->fetch()){$price=($v['sale_price']!==null&&$v['sale_price']<$v['price'])?$v['sale_price']:$v['price'];$line=$price*$qty;$subtotal+=$line;$lines[]=['v'=>$v,'qty'=>$qty,'price'=>$price,'line'=>$line];}}}$flash=$_SESSION['flash']??null;unset($_SESSION['flash']);include __DIR__.'/includes/admin_header.php';
?>
<div class="admin-page-heading"><div><h1>Billing (POS)</h1><p>Create bills and manage customer purchases.</p></div><a class="admin-btn" href="billing.php?clear=1">Clear Cart</a></div>
<?php if($flash):?><div class="admin-alert admin-alert-<?=h($flash['type'])?>"><?=h($flash['message'])?><?php if($order):?> <a href="billing.php?receipt=<?=$order?>">Print receipt</a><?php endif;?></div><?php endif;?>
<div class="billing-grid">
<section class="admin-panel"><div class="admin-panel-head"><h2>Select Products</h2></div><div class="billing-search"><input id="billSearch" type="search" placeholder="⌕ Search products by name..."></div><div class="billing-product-list">
<?php foreach($products as $v):$price=($v['sale_price']!==null&&$v['sale_price']<$v['price'])?$v['sale_price']:$v['price'];?><div class="billing-row" data-name="<?=h(strtolower($v['name']))?>"><div class="billing-thumb"><?=bill_icon($v['name'])?></div><div><div class="billing-name"><?=h($v['name'])?></div><div class="billing-meta">₹<?=number_format($price,2)?> / <?=h($v['unit'])?> · <?=$v['stock']?> available</div></div><form method="post" style="display:flex;gap:5px;align-items:center"><input type="hidden" name="csrf_token" value="<?=h(csrf_token())?>"><input type="hidden" name="vegetable_id" value="<?=$v['id']?>"><input type="number" name="quantity" min="1" max="<?=$v['stock']?>" value="1" style="width:50px;height:31px;border:1px solid #d8e1dc;border-radius:7px;padding:0 5px"><button class="billing-add" name="add_item" value="1">＋</button></form></div><?php endforeach;?></div></section>
<section class="admin-panel"><div class="admin-panel-head"><h2>Current Bill</h2><span style="font-size:11px;color:#df2e24;font-weight:700"><?=count($lines)?> item(s)</span></div><div class="billing-cart">
<?php if($lines):?><table class="billing-cart-table"><thead><tr><th>Product</th><th>Qty</th><th>Price</th><th>Total</th></tr></thead><tbody><?php foreach($lines as $x):?><tr><td><?=bill_icon($x['v']['name'])?> <?=h($x['v']['name'])?></td><td><?=$x['qty']?> <?=h($x['v']['unit'])?></td><td>₹<?=number_format($x['price'],2)?></td><td>₹<?=number_format($x['line'],2)?></td></tr><?php endforeach;?></tbody></table>
<div class="billing-summary"><div class="billing-summary-line"><span>Subtotal</span><strong>₹<?=number_format($subtotal,2)?></strong></div></div>
<form method="post"><input type="hidden" name="csrf_token" value="<?=h(csrf_token())?>"><input type="hidden" name="checkout" value="1"><div class="admin-form-grid"><div class="admin-field"><label>Customer</label><input name="customer_name" value="Walk-in Customer" required></div><div class="admin-field"><label>Phone</label><input name="phone" value="0000000000"></div><div class="admin-field"><label>Email</label><input type="email" name="email" value="walkin@local"></div><div class="admin-field"><label>Address</label><input name="address" value="Store counter"></div><div class="admin-field"><label>Discount (%)</label><input id="discount" type="number" name="discount_percent" min="0" max="100" step=".01" value="0"></div><div class="admin-field"><label>Payment</label><select name="payment_method"><option value="cash">Cash Payment</option><option value="upi_qr">UPI Payment</option></select></div></div><div class="billing-summary"><div class="billing-summary-line"><span>Discount</span><strong id="discountValue">- ₹0.00</strong></div><div class="billing-total"><span>Total Payable</span><strong id="grandTotal">₹<?=number_format($subtotal,2)?></strong></div></div><div class="payment-grid"><button type="submit" name="checkout" value="1" class="active">Checkout & Create Bill</button><a class="admin-btn" href="billing.php?clear=1">Clear</a></div></form><?php else:?><div class="admin-empty">Your bill is empty.<br>Add products from the left.</div><?php endif;?></div></section></div>
<script>const bs=document.getElementById('billSearch');bs?.addEventListener('input',()=>{const q=bs.value.toLowerCase();document.querySelectorAll('.billing-row').forEach(r=>r.style.display=r.dataset.name.includes(q)?'':'none')});const d=document.getElementById('discount'),dv=document.getElementById('discountValue'),gt=document.getElementById('grandTotal'),sub=<?=json_encode($subtotal)?>;function calc(){const p=Math.min(100,Math.max(0,parseFloat(d?.value||0)));const x=sub*p/100;dv.textContent='- ₹'+x.toFixed(2);gt.textContent='₹'+(sub-x).toFixed(2)}d?.addEventListener('input',calc);</script>
<?php include __DIR__.'/includes/admin_footer.php';
