<?php
require_once __DIR__ . '/includes/auth.php';require_role(['admin','staff']);$page_title='Reports';
$start=$_GET['start']??date('Y-m-01');$end=$_GET['end']??date('Y-m-d');if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$start))$start=date('Y-m-01');if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$end))$end=date('Y-m-d');if($start>$end){$tmp=$start;$start=$end;$end=$tmp;}
$st=$pdo->prepare("SELECT COALESCE(SUM(oi.subtotal),0) revenue, COALESCE(SUM(oi.quantity*oi.cost_price),0) cost, COUNT(DISTINCT o.id) orders FROM orders o JOIN order_items oi ON oi.order_id=o.id WHERE o.payment_status='paid' AND DATE(o.created_at) BETWEEN ? AND ?");$st->execute([$start,$end]);$r=$st->fetch();$w=$pdo->prepare("SELECT COALESCE(SUM(w.quantity*v.cost_price),0) loss FROM wastage w JOIN vegetables v ON v.id=w.vegetable_id WHERE DATE(w.created_at) BETWEEN ? AND ?");$w->execute([$start,$end]);$waste=(float)$w->fetchColumn();$revenue=(float)$r['revenue'];$cost=(float)$r['cost'];$gross=$revenue-$cost;$net=$gross-$waste;
$top=$pdo->prepare("SELECT oi.name,SUM(oi.subtotal) amount,SUM(oi.quantity) qty FROM orders o JOIN order_items oi ON oi.order_id=o.id WHERE o.payment_status='paid' AND DATE(o.created_at) BETWEEN ? AND ? GROUP BY oi.vegetable_id,oi.name ORDER BY amount DESC LIMIT 5");$top->execute([$start,$end]);$topProducts=$top->fetchAll();
$days=[];$cursor=new DateTime($start);$finish=new DateTime($end);$finish->modify('+1 day');while($cursor<$finish && count($days)<31){$d=$cursor->format('Y-m-d');$q=$pdo->prepare("SELECT COALESCE(SUM(total_amount),0) FROM orders WHERE payment_status='paid' AND order_status<>'cancelled' AND DATE(created_at)=?");$q->execute([$d]);$days[]=['date'=>$d,'value'=>(float)$q->fetchColumn()];$cursor->modify('+1 day');}$max=max(1,...array_column($days,'value'));
include __DIR__.'/includes/admin_header.php';
?>
<div class="admin-page-heading"><div><h1>Reports (P&amp;L)</h1><p>Analyze your business performance and profits for a selected time frame.</p></div><a class="admin-btn" href="export_orders.php?start=<?=h($start)?>&end=<?=h($end)?>">⇩ Download Report</a></div>
<form class="admin-filter-bar report-filter" method="get"><div class="admin-field"><label>Start Date</label><input type="date" name="start" value="<?=h($start)?>"></div><span style="padding-bottom:10px;color:#7a8580;font-size:12px">to</span><div class="admin-field"><label>End Date</label><input type="date" name="end" value="<?=h($end)?>"></div><button class="admin-btn admin-btn-primary" type="submit">Filter</button></form>
<div class="report-cards"><div class="report-card"><div class="label">Total Sales</div><div class="value">₹<?=number_format($revenue,2)?></div><div class="trend">↑ Selected period</div></div><div class="report-card"><div class="label">Total Cost</div><div class="value">₹<?=number_format($cost,2)?></div><div class="trend">Product cost</div></div><div class="report-card"><div class="label">Gross Profit</div><div class="value">₹<?=number_format($gross,2)?></div><div class="trend">Sales − product cost</div></div><div class="report-card"><div class="label">Net Profit</div><div class="value">₹<?=number_format($net,2)?></div><div class="trend">After wastage loss</div></div></div>
<div class="report-grid"><section class="admin-panel"><div class="admin-panel-head"><h2>Sales Overview <small>(Selected Period)</small></h2><span style="font-size:11px;color:#68736f"><?=number_format((int)$r['orders'])?> paid order(s)</span></div><div class="report-chart"><svg viewBox="0 0 760 260" preserveAspectRatio="none" aria-label="Sales overview chart"><line x1="0" y1="220" x2="760" y2="220" stroke="#dfe7e2"/><line x1="0" y1="165" x2="760" y2="165" stroke="#edf2ef"/><line x1="0" y1="110" x2="760" y2="110" stroke="#edf2ef"/><line x1="0" y1="55" x2="760" y2="55" stroke="#edf2ef"/><polyline fill="none" stroke="#087354" stroke-width="4" points="<?php foreach($days as $i=>$d){$x=count($days)>1?($i/(count($days)-1))*760:380;$y=220-($d['value']/$max)*175;echo number_format($x,1).','.number_format($y,1).' ';}?>"/></svg><div class="sales-axis"><span><?=h($start)?></span><span><?=h($end)?></span></div></div></section><section class="admin-panel top-products"><div class="admin-panel-head"><h2>Top Selling Products</h2></div><div class="admin-product-list"><?php foreach($topProducts as $i=>$p):?><div class="admin-product-row"><span class="top-rank"><?=$i+1?>.</span><div><div class="admin-product-name"><?=h($p['name'])?></div><div class="admin-product-meta"><?=number_format($p['qty'],1)?> units sold</div></div><span class="admin-product-price">₹<?=number_format($p['amount'],2)?></span></div><?php endforeach;if(!$topProducts):?><div class="admin-empty">No sales in this period.</div><?php endif;?></div></section></div>
<div class="admin-panel" style="margin-top:18px"><div class="admin-panel-head"><h2>Profit Summary</h2></div><div style="padding:0 20px 20px"><div class="billing-summary-line"><span>Sales Revenue</span><strong>₹<?=number_format($revenue,2)?></strong></div><div class="billing-summary-line"><span>Product Cost</span><strong>− ₹<?=number_format($cost,2)?></strong></div><div class="billing-summary-line"><span>Gross Profit</span><strong>₹<?=number_format($gross,2)?></strong></div><div class="billing-summary-line"><span>Wastage Loss</span><strong>− ₹<?=number_format($waste,2)?></strong></div><div class="billing-total"><span>Net Profit</span><strong>₹<?=number_format($net,2)?></strong></div><p style="font-size:11px;color:#7a8580;margin:12px 0 0">Cost uses the purchase cost captured on each billing order item. Older online orders without a cost snapshot may show zero product cost.</p></div></div>
<?php include __DIR__.'/includes/admin_footer.php';
