<?php
require_once __DIR__ . '/includes/auth.php';
require_role('admin');
$page_title = 'Staff & Admin Users';

if($_SERVER['REQUEST_METHOD']==='POST'){require_csrf();$username=trim($_POST['username']??'');$password=$_POST['password']??'';$role=in_array($_POST['role']??'', ['admin','staff'],true)?$_POST['role']:'staff';if(strlen($username)<3||strlen($password)<6)$_SESSION['flash']=['type'=>'error','message'=>'Username must be 3+ characters and password 6+ characters.'];else{try{$st=$pdo->prepare("INSERT INTO admins (username,password,role) VALUES (?,?,?)");$st->execute([$username,password_hash($password,PASSWORD_DEFAULT),$role]);$_SESSION['flash']=['type'=>'success','message'=>'User created.'];}catch(PDOException $e){$_SESSION['flash']=['type'=>'error','message'=>'Could not create user; username may already exist.'];}}header('Location: users.php');exit;}
$q=$pdo->prepare("SELECT id,username,role,created_at FROM admins ORDER BY id"); $q->execute(); $users=$q->fetchAll();$flash=$_SESSION['flash']??null;unset($_SESSION['flash']);include __DIR__.'/includes/admin_header.php';?>
<div class="section-head" style="text-align:left;margin-top:0"><h2 style="display:block">Staff &amp; Admin Users</h2><p>Create separate accounts instead of sharing the admin password.</p></div>
<?php if($flash):?><div class="alert alert-<?=h($flash['type'])?>"><?=h($flash['message'])?></div><?php endif;?>
<div class="form-card" style="max-width:560px"><form method="post"><input type="hidden" name="csrf_token" value="<?=h(csrf_token())?>"><div class="form-group"><label>Username</label><input name="username" required minlength="3" maxlength="50"></div><div class="form-group"><label>Password</label><input type="password" name="password" required minlength="6"></div><div class="form-group"><label>Role</label><select name="role"><option value="staff">Staff</option><option value="admin">Admin</option></select></div><button class="btn btn-primary">Create User</button></form></div>
<div class="table-wrap" style="margin-top:25px"><table><tr><th>Username</th><th>Role</th><th>Created</th></tr><?php foreach($users as $u):?><tr><td><?=h($u['username'])?></td><td><?=h(ucfirst($u['role']))?></td><td><?=h(format_ist($u['created_at']))?></td></tr><?php endforeach;?></table></div>
<?php include __DIR__.'/includes/admin_footer.php';