<?php
require_once __DIR__ . '/includes/auth.php';require_role(['admin','staff']);$page_title='Wastage';
if($_SERVER['REQUEST_METHOD']==='POST'){require_csrf();$id=(int)$_POST['vegetable_id'];$qty=max(1,(int)$_POST['quantity']);$reason=$_POST['reason']??'';$notes=trim($_POST['notes']??'');if(!in_array($reason,['Expired','Damaged','Spoiled','Other'],true))$_SESSION['flash']=['type'=>'error','message'=>'Invalid wastage reason.'];else{try{$pdo->beginTransaction();$st=$pdo->prepare("SELECT id,name,stock FROM vegetables WHERE id=? FOR UPDATE");$st->execute([$id]);$v=$st->fetch();if(!$v||$v['stock']<$qty)throw new Exception('Insufficient stock for wastage.');$u=$pdo->prepare("UPDATE vegetables SET stock=stock-? WHERE id=? AND stock>=?");$u->execute([$qty,$id,$qty]);if($u->rowCount()!==1)throw new Exception('Stock changed. Please retry.');$i=$pdo->prepare("INSERT INTO wastage (vegetable_id,quantity,reason,notes,created_by) VALUES (?,?,?,?,?)");$i->execute([$id,$qty,$reason,$notes?:null,$_SESSION['admin_id']]);$wid=$pdo->lastInsertId();$m=$pdo->prepare("INSERT INTO inventory_movements (vegetable_id,movement_type,quantity,reference_id,notes,created_by) VALUES (?,'wastage',?,?,?,?)");$m->execute([$id,-$qty,$wid,$reason.($notes?' - '.$notes:''),$_SESSION['admin_id']]);$pdo->commit();$_SESSION['flash']=['type'=>'success','message'=>'Wastage recorded and stock reduced.'];}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$_SESSION['flash']=['type'=>'error','message'=>'Could not record wastage: '.$e->getMessage()];}}header('Location: wastage.php');exit;}
$q=$pdo->prepare("SELECT id,name,stock,unit FROM vegetables WHERE is_active=1 ORDER BY name");$q->execute();$products=$q->fetchAll();$q=$pdo->prepare("SELECT w.*,v.name,a.username FROM wastage w JOIN vegetables v ON v.id=w.vegetable_id LEFT JOIN admins a ON a.id=w.created_by ORDER BY w.created_at DESC LIMIT 100");$q->execute();$rows=$q->fetchAll();$flash=$_SESSION['flash']??null;unset($_SESSION['flash']);$qtyTotal=0;$valueTotal=0;$reasons=[];foreach($rows as $r){$qtyTotal+=(float)$r['quantity'];$reasons[$r['reason']]=($reasons[$r['reason']]??0)+1;}
$commonReason=$reasons?array_search(max($reasons),$reasons):'—';include __DIR__.'/includes/admin_header.php';
?>
<div class="admin-page-heading"><div><h1>Wastage</h1><p>Record and manage vegetable wastage and stock losses.</p></div><div class="admin-page-actions"><div class="admin-field"><label>Start Date</label><input type="date" id="wStart"></div><div class="admin-field"><label>End Date</label><input type="date" id="wEnd"></div></div></div>
<?php if($flash):?><div class="admin-alert admin-alert-<?=h($flash['type'])?>"><?=h($flash['message'])?></div><?php endif;?>
<div class="admin-card-grid"><div class="admin-mini-card"><span class="label">Total Wastage (Qty)</span><span class="value"><?=number_format($qtyTotal,1)?> kg</span><span class="hint">Latest 100 records</span></div><div class="admin-mini-card"><span class="label">Wastage Records</span><span class="value"><?=number_format(count($rows))?></span><span class="hint">Tracked records</span></div><div class="admin-mini-card"><span class="label">Most Common Reason</span><span class="value" style="font-size:18px"><?=h($commonReason)?></span><span class="hint">Based on records shown</span></div><div class="admin-mini-card"><span class="label">Stock Control</span><span class="value" style="font-size:18px">Atomic</span><span class="hint">Stock reduces with each record</span></div></div>
<div class="wastage-layout"><section class="admin-form-card"><div class="admin-panel-head" style="padding:0 0 15px"><h2>Add Wastage Record</h2></div><form method="post"><input type="hidden" name="csrf_token" value="<?=h(csrf_token())?>"><div class="admin-field"><label>Product</label><select name="vegetable_id" required><?php foreach($products as $v):?><option value="<?=$v['id']?>"><?=h($v['name'])?> — <?=$v['stock']?> <?=h($v['unit'])?> available</option><?php endforeach;?></select></div><div class="admin-form-grid" style="margin-top:14px"><div class="admin-field"><label>Quantity</label><input type="number" name="quantity" min="1" required></div><div class="admin-field"><label>Reason</label><select name="reason" required><option>Expired</option><option>Damaged</option><option>Spoiled</option><option>Other</option></select></div></div><div class="admin-field" style="margin-top:14px"><label>Notes</label><input name="notes" maxlength="255" placeholder="Optional details"></div><div class="admin-form-actions"><button class="admin-btn admin-btn-primary" type="submit">＋ Record Wastage</button></div></form></section>
<section class="admin-table-wrap"><div class="admin-panel-head"><h2>Wastage Records</h2><span style="font-size:11px;color:#68736f">Latest 100</span></div><table class="admin-table" id="wastageTable"><thead><tr><th>Date</th><th>Product</th><th>Quantity</th><th>Reason</th><th>Notes</th><th>By</th></tr></thead><tbody><?php foreach($rows as $r):$rc=strtolower($r['reason']);?><tr data-date="<?=date('Y-m-d',strtotime($r['created_at']))?>"><td><?=h(date('d M Y',strtotime($r['created_at'])))?></td><td class="product-cell"><?=h($r['name'])?></td><td><?=h($r['quantity'])?></td><td><span class="reason-badge reason-<?=h($rc)?>"><?=h($r['reason'])?></span></td><td><?=h($r['notes']??'—')?></td><td><?=h($r['username']??'—')?></td></tr><?php endforeach;if(!$rows):?><tr><td colspan="6" class="admin-empty">No wastage records yet.</td></tr><?php endif;?></tbody></table></section></div>
<script>const ws=document.getElementById('wStart'),we=document.getElementById('wEnd');function wf(){document.querySelectorAll('#wastageTable tbody tr[data-date]').forEach(r=>r.style.display=((!ws.value||r.dataset.date>=ws.value)&&(!we.value||r.dataset.date<=we.value))?'':'none')}ws.addEventListener('change',wf);we.addEventListener('change',wf);</script>
<?php include __DIR__.'/includes/admin_footer.php';
